### ISSUE TITLE
Leading spaces not being removed on Windows

### ISSUE THREAD

**Issue by pyrmont** [pyrmont/documentarian#13]
There's an issue with leading spaces that #12 is an attempt to fix.

@strangepete Can you provide the specific text that's causing the issue? I'd like to keep the bug report separate from the potential PR if that makes sense.

**Comment by strangepete** [comment]
Sure, and sorry for not filing an issue first, a little over confident hah

Windows 10
Janet 1.37.1
using documentarian installed via jpm install [git url]

This is the rendered output (a portion, but it all looks the same) I get when the template has two leading spaces. The sections that follow a markdown list with two spaces are interpreted as being a multiline list item, and are indented as such:

----

  ## spi/read-opt

  **cfunction**  | [source][31]

  ```janet
  (spi/read-opt channel &opt kw ...)
  ```

  Set SPI Read transfer options. Takes zero, or more keywords:

* `:size-in-bits`      - Transfer size in bits (default is bytes)
* `:cs`                - Chip-select line asserted before beginning transfer




  [31]: c/spi.c#L331

  ## spi/readwrite

  **cfunction**  | [source][32]

  ```janet
  (spi/readwrite channel size sendbuf recvbuf)
  ```

  Simultaneously read & write `size` n-bytes to `channel`.

Returns bytes transfered. Sets `:err` to return status.

Note: Uses the `write-opt` transfer option for both operations.

This is a **blocking function**.

  [32]: c/spi.c#L505

----

And this is the block above verbatim; note some sections retain the double-space, others sit flat. (Had to \ escape the inner quotes to get it to render here, but otherwise the same)

```
  ## spi/read-opt

  **cfunction**  | [source][31]

  \```janet
  (spi/read-opt channel &opt kw ...)
  \```

  Set SPI Read transfer options. Takes zero, or more keywords:

* `:size-in-bits`      - Transfer size in bits (default is bytes)
* `:cs`                - Chip-select line asserted before beginning transfer




  [31]: c/spi.c#L331

  ## spi/readwrite

  **cfunction**  | [source][32]

  \```janet
  (spi/readwrite channel size sendbuf recvbuf)
  \```

  Simultaneously read & write `size` n-bytes to `channel`.

Returns bytes transfered. Sets `:err` to return status.

Note: Uses the `write-opt` transfer option for both operations.

This is a **blocking function**.

  [32]: c/spi.c#L505
```

**Comment by pyrmont** [comment]
@strangepete Thanks for that. Sorry, I gather this can be ‘fixed’ by just changing the template but I’m curious to see the input, too. Is that publicly available somewhere? If not, would it be possible to put one of the files that you’re using to generate the doc in a Gist?

**Comment by strangepete** [comment]
Of course, I completely forgot!

Edit: uploaded the project here -- https://github.com/strangepete/janet-libMPSSE

I'll include just the fragments of what generates the docstrings posted above --

```
JANET_FN(cfun_spi_set_read_options,
    "(spi/read-opt channel &opt kw ...)",
    "Set SPI Read transfer options. Takes zero, or more keywords:\n\n"
    "* `:size-in-bits`      - Transfer size in bits (default is bytes)\n"
    "* `:cs`                - Chip-select line asserted before beginning transfer\n\n") {
    janet_arity(argc, 1, 3);

    channel_t *c = (channel_t *)janet_getabstract(argv, 0, &channel_type);
    c->read_options = spi_transfer_option_keywords(argc, argv);
    return set_status_dyn(FT_OK, janet_wrap_nil());
}
-----
JANET_FN(cfun_spi_readwrite,
    "(spi/readwrite channel size sendbuf recvbuf)",
    "Simultaneously read & write `size` n-bytes to `channel`.\n\n"
    "Returns bytes transfered. Sets `:err` to return status.\n\n"
    "Note: Uses the `write-opt` transfer option for both operations.\n\n"
    "This is a **blocking function**.") {
    janet_fixarity(argc, 4);
[...]
```

**Comment by pyrmont** [comment]
@strangepete Thanks for that. I’d like to see if I can land a fix in Janet that would support dedenting on Windows platforms so will see how that goes first. Apologies for the delay!

**Comment by strangepete** [comment]
No need for apology! That'd be fantastic, so I'll close that pull again :D

**Comment by strangepete** [comment]
All set with #1534, just installed a fresh copy and output looks perfect. Thank you for the effort, much appreciated!

**Comment by pyrmont** [comment]
No problems! Glad it got there in the end. Look forward to a new official release coming soon :)
